name: AppImage Creator

on:
  push:
    branches: [ ci-appimage ]
  pull_request:
    branches: [ ci-appimage  ]

jobs:
  build-appimage:

    runs-on: ubuntu-20.04  #ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      #- run: 
      - name: install dependencies  # DEBIAN_FRONTEND=noninteractive 
        run: |
          sudo apt-get -y update
          sudo apt-get -y install curl build-essential pkg-config bison flex autoconf automake libtool 
          sudo apt-get -y install make git libssl-dev python2 python-wxgtk3.0 libssl-dev libxml2-dev
          sudo apt-get -y install libxslt1-dev python2-dev 'libpng*' libfreetype6-dev  
          # Including pip for python2.7
          curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
          sudo python2 get-pip.py

          # sudo apt-get -y -qq install curl
          # sudo apt-get -y -qq install build-essential
          # sudo apt-get -y -qq install pkg-config 
          # sudo apt-get -y -qq install bison
          # sudo apt-get -y -qq install flex 
          # sudo apt-get -y -qq install autoconf 
          # sudo apt-get -y -qq install automake 
          # sudo apt-get -y -qq install libtool 
          # sudo apt-get -y -qq install make 
          # sudo apt-get -y -qq install git 
          # sudo apt-get -y -qq install libssl-dev
          # sudo apt-get -y -qq install python2
          # sudo apt-get -y -qq install python2.7
          # sudo apt-get -y -qq install python-wxgtk3.0
          # sudo apt-get -y -qq install libssl-dev
          # sudo apt-get -y -qq install libxml2-dev libxslt1-dev
          # sudo apt-get -y -qq install python2-dev
          # sudo apt-get -y -qq install python2.7-dev
          # sudo apt-get -y -qq install 'libpng*'
          #sudo apt-get -y -qq install libpng12-dev 
          #sudo apt-get -y -qq install libfreetype6-dev
          #export ARCH=x86_64
          #virtualenv -p python2 usr
          #python2 -m pip install --system --ignore-installed --prefix=/usr --root=AppDir
          #mkdir -p AppDir
          #mv editor AppDir/
          #echo "python editor/Beremiz.py" > AppRun
          #chmod +x AppDir/AppRun  
            
      - name: create virtual environment 
        run: |
          python2 -v 
          sudo pip2 install virtualenv  
          #virtualenv -p python2 usr

      - name: Build AppImage
        uses: AppImageCrafters/build-appimage-action@master
        env:
          UPDATE_INFO: gh-releases-zsync|AppImageCrafters|appimage-demo-qt5|latest|*x86_64.AppImage.zsync
        with:
          recipe: AppImageBuilder.yml
      - uses: actions/upload-artifact@v2
        with:
          name: AppImage
          path: './*.AppImage*'