name: C/C++ AppImage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-appimage:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get -y -qq update
          sudo apt-get -y -qq install curl build-essential pkg-config bison flex autoconf automake libtool make git libssl-dev
          sudo apt-get -y -qq install python2
          sudo apt-get -y -qq install python2.7
          sudo apt-get -y -qq install python-wxgtk3.0
          sudo apt-get -y -qq install libssl-dev
          sudo apt-get -y -qq install libxml2-dev libxslt1-dev
          sudo apt-get -y -qq install python2-dev
          sudo apt-get -y -qq install python2.7-dev
          sudo apt-get -y -qq install libpng
          sudo apt-get -y -qq install libpng-dev libfreetype6-dev          

      - name: Build AppImage
        uses: AppImageCrafters/build-appimage-action@master
        env:
          UPDATE_INFO: gh-releases-zsync|AppImageCrafters|appimage-demo-qt5|latest|*x86_64.AppImage.zsync
        with:
          recipe: AppImageBuilder.yml
      - uses: actions/upload-artifact@v2
        with:
          name: AppImage
          path: './*.AppImage*'